In [7]:
import numpy as np

arr1 = np.array([1,2,3,4,4])
print(arr1)
print(type(arr1))
print(arr1.shape)



[1 2 3 4 4]
<class 'numpy.ndarray'>
(5,)


In [2]:
arr2 = np.array([1,1,2,2,3,3,4,4])
arr2.reshape(4,2)


array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
arr = np.arange(0, 40, 2)
arr = arr.reshape(5,4)
print(arr)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]]


In [ ]:
arr[1:,2:] # row, column ( includes the numbered index )

array([[12, 14],
       [20, 22],
       [28, 30],
       [36, 38]])

In [25]:
arr[1:2, 2:3]

array([[12]])

In [27]:
print(np.mean(arr))
print(np.std(arr))

19.0
11.532562594670797
